AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with security group in default VPC

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound SSH, RDP, and HTTP
      VpcId: vpc-0c93566e15b942de4 # Replace with your default VPC ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-021a584b49225376d # Replace with your desired AMI
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: subnet-0913ca5758b0c90e1 # Replace with a subnet ID in your default VPC
      KeyName: pass # Replace with your EC2 key pair name

Outputs:
  InstanceId:
    Description: The ID of the EC2 instance
    Value: !Ref MyEC2Instance
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
